### ISSUE TITLE
`${editor_info[keymap]}` would be sometimes popped up

### ISSUE THREAD

**Issue by kepbod** [sindresorhus/pure#230]
I set vi keybindings according to https://github.com/sindresorhus/pure/wiki#show-current-mode-when-using-vi-keybindings. But `${editor_info[keymap]}` would be sometimes popped up. It would not happen before. It only occurred after I updated pure to the latest version. How could I solve this problem? Thanks a lot.

**Comment by mafredri** [comment]
Looks like this was an unfortunate side-effect of https://github.com/sindresorhus/pure/commit/780d1a5a08589afa051271bbe6c74c1f2e05c368. I just pushed a PR that fixes this, feel free to try it out.

**Comment by kepbod** [comment]
I have tried it. But it seems like that this RP did not solve this problem.

**Comment by mafredri** [comment]
That's weird, I managed to reproduce your problem and fix it on my machine.

Before you do anything else, could you run this command and give me the output (it assumes you are using the PR branch)?
```
zsh --version; zmodload zsh/parameter; print prompt_subst: $options[prompt_subst]; print preprompt: $(whence -f prompt_pure_preprompt_render | grep 'setopt prompt_subst')
```

And finally, it would be great if you could answer the following questions:

1. Are you still using prezto? I assume you are.
2. Could it be the prezto bundled pure that gets activated, instead of the on in my PR?
3. Could you try version 1.4.0 of pure (https://github.com/sindresorhus/pure/commit/211b49481e1279f1747622e3885d405a977362ff), if yes, does it also exhibit this problem?

**Comment by kepbod** [comment]
Sorry, I think it is my fault. It worked well and fix this bug. Thanks very much!
