### ISSUE TITLE
Error since zsh 5.3 upgrade

### ISSUE THREAD

**Issue by harukizaemon** [sindresorhus/pure#258]
```
❯ 
 prompt_pure_async_callback:13: bad math expression: operand expected at `> 2 '

❯ zsh --version
zsh 5.3 (x86_64-apple-darwin16.1.0)

❯ which zsh
/usr/local/bin/zsh
```

**Comment by mafredri** [comment]
I believe I fixed this a while back, could you please try the latest (master) of [zsh-async](https://github.com/mafredri/zsh-async). Is it still reproducible with it?

**Comment by mafredri** [comment]
@harukizaemon I just pushed the update to pure, so you can just update to the latest master of pure and the issue should be resolved.

**Comment by felixfoertsch** [comment]
Hm, I tinkered around with it and thought it might be a slimzsh issue, but I think -- for me at least -- the issue is still present in pure.

**Comment by mafredri** [comment]
@felixfoertsch could you elaborate? What exactly is your issue? Did you try to update pure (https://github.com/sindresorhus/pure/commit/787cab6d89889402dd06d769d03cf70baa0fbd8c)?

**Comment by felixfoertsch** [comment]
@mafredri thanks! I had the exact same issue @harukizaemon posted.

I manually replaced the async.zsh and now the error is gone. It would not go away with just pulling from the repo.

**Comment by mafredri** [comment]
Pure v1.4.1 is now released, which fixes this issue 🎉. Sorry for the inconvenience, I should've updated zsh-async last month when I found the issue 😝.

**Comment by harukizaemon** [comment]
The latest update has fixed the issue for me. Thank you!

**Comment by gabrielfreiberg** [comment]
I'm also having this issue. Using antigen to load in pure. How would I go about updating?

**Comment by Alex-Werner** [comment]
`prompt_pure_async_callback:13: bad math expression: operand expected at `> 2 '1

Hi, I do have the same problem on zsh 5.4.2 (x86_64-apple-darwin17.0.0)
I'm using lambda-pure (https://github.com/marszall87/lambda-pure/blob/master/lambda-pure.zsh), can it be linked to you or should I see that myself ? (maintainer of lambda-pure seems to not update it anymore)

**Comment by mafredri** [comment]
@Alex-Werner you should raise this issue over at lambda-pure, we don't provide support for forks. Happy to help if you can reproduce in Pure.
