### ISSUE TITLE
Pure prompt shows variables instead of their substituted values

### ISSUE THREAD

**Issue by ramlev** [sindresorhus/pure#401]
### General information

- Pure version: 1.7.0
- ZSH version: zsh 5.5.1 (x86_64-apple-darwin17.5.0)
- Terminal program & version: iterm2 Build 3.1.6
- Operating system: high sierra 10.13.4 (17E199)
- ZSH framework: antibody

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
after updated the antibody to 3.4.5 and pure to 1.7.0 this is my terminal after opening

```
zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-up'
zsh-syntax-highlighting: (This is sometimes caused by doing `bindkey <keys> history-substring-search-up` without creating the 'history-substring-search-up' widget with `zle -N` or `zle -C`.)
zsh-syntax-highlighting: unhandled ZLE widget 'clear-history'
zsh-syntax-highlighting: (This is sometimes caused by doing `bindkey <keys> clear-history` without creating the 'clear-history' widget with `zle -N` or `zle -C`.)
zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-down'
zsh-syntax-highlighting: (This is sometimes caused by doing `bindkey <keys> history-substring-search-down` without creating the 'history-substring-search-down' widget with `zle -N` or `zle -C`.)

~
${PURE_PROMPT_SYMBOL:-❯}
```

and if i'm in a git repo

```
~/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-sindresorhus-SLASH-pure ${prompt_pure_vcs_info[branch]}${prompt_pure_git_dirty}
${PURE_PROMPT_SYMBOL:-❯}
```

### Reproduction steps

1. open iterm2

### My `.zshrc`:

```
source <(antibody init)

antibody bundle < ~/.zsh/antibody-bundles.txt
```

and my antibody-bundles.txt

```
mafredri/zsh-async
ramlev/zsh-plugins
zsh-users/zsh-completions
zsh-users/zsh-autosuggestions
sindresorhus/pure
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-history-substring-search
```

**Comment by mafredri** [comment]
I'm curious why you think this correlates with the Pure update. Can you reproduce it with 1.6.0?

Either way, you are probably turning off `PROMPT_SUBST` somewhere.

`setopt promptsubst` will fix it.

**Comment by ramlev** [comment]
sorry, but how am i able to reinstall the old version 1.6.0?



//Hasse

**Comment by ramlev** [comment]
the setopt promptsubst will fix the prompt issue, bus still getting this

```
zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-up'
zsh-syntax-highlighting: (This is sometimes caused by doing `bindkey <keys> history-substring-search-up` without creating the 'history-substring-search-up' widget with `zle -N` or `zle -C`.)
zsh-syntax-highlighting: unhandled ZLE widget 'clear-history'
zsh-syntax-highlighting: (This is sometimes caused by doing `bindkey <keys> clear-history` without creating the 'clear-history' widget with `zle -N` or `zle -C`.)
zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-down'
zsh-syntax-highlighting: (This is sometimes caused by doing `bindkey <keys> history-substring-search-down` without creating the 'history-substring-search-down' widget with `zle -N` or `zle -C`.)
```
and haven't changed anything but executed

	antibody update

**Comment by mafredri** [comment]
> sorry, but how am i able to reinstall the old version 1.6.0?

I can't help you with antibody, but if it's just a git repo, you can `git checkout v1.6.0`.

> the setopt promptsubst will fix the prompt issue, bus still getting this

Can't really help here either, those errors are not coming from Pure.

**Comment by pkruithof** [comment]
I don't know what causes it, but the same thing happens to me using [zplug](https://github.com/zplug/zplug):

```
zplug "sindresorhus/pure"
```

prompt:

```
~/.dotfiles ${prompt_pure_vcs_info[branch]}${prompt_pure_git_dirty} ${prompt_pure_git_arrows}
${PURE_PROMPT_SYMBOL:-❯} 
```

using 1.7.0 (or 1.6.0 for that matter) works:

```
zplug "sindresorhus/pure", at:v1.7.0
```

prompt:

```
~/.dotfiles master* ⇡
❯ 
```

**Comment by pkruithof** [comment]
I've found the commit at which it stopped working:

```
zplug "sindresorhus/pure", at:17e23aecda563f6135b91d0d2eea82dadb0ca070
```

```
~
${PURE_PROMPT_SYMBOL:-❯}
```

Still not sure what causes it, or if it's pure's "fault", though. But maybe it helps.

**Comment by mafredri** [comment]
Ah, of course... 

https://github.com/sindresorhus/pure/blob/17e23aecda563f6135b91d0d2eea82dadb0ca070/pure.zsh#L113

We're setting local options now, preventing `setopt promptsubst` done a few lines below from taking effect outside the function 🤦‍♂️.

**Comment by mafredri** [comment]
Fixed in c74d5dd, thanks tracking down the commit @pkruithof! I did not spot this myself because my own configuration sets `promptsubst`.

**Comment by ltartari** [comment]
Mine is still broken… but I couldn't figure out why.

Calling `setopt promptsubst` after `antigen init .antigenrc` in my .zshrc seems to fix it.

![image](https://user-images.githubusercontent.com/114248/39472957-bbc2b4b4-4d22-11e8-8159-e2b9e55a46d5.png)

I'm using a brewed version antigen if that makes any difference.

**Comment by ramlev** [comment]
Mine is also still broken like @ltartari explained.

**Comment by mafredri** [comment]
@ltartari, @ramlev did you update to latest master, please check.

**Comment by ltartari** [comment]
I am. I've included on the attached screenshot in the previous message, @mafredri .

As mentioned I'm using a brewed version of antigen… here's my `.antigenrc` if that helps:
```
antigen bundles <<EOBUNDLES
  compleat
  git-extras
  git-flow
  osx
  zsh-users/zsh-syntax-highlighting

  mafredri/zsh-async
  sindresorhus/pure
EOBUNDLES

antigen apply
```

**Comment by ramlev** [comment]
```
${PURE_PROMPT_SYMBOL:-❯} git rev-parse HEAD
c74d5dd3dd2a37d009feb77c5d715d2c4c2a981c
```

Yes i did.

**Comment by mafredri** [comment]
I'm unable to reproduce on any versions of Zsh, even when I do:

```zsh
setopt nopromptsubst
prompt pure
```

**Comment by mafredri** [comment]
Latest commit (5a39be4e8fb9dc93af25943440e03234e734b933) should fix all issues, except yours @ltartari. I think it's an antigen issue, did not work any better with older versions of Pure (tried 1.6.0, 1.7.0 and master).

**Comment by ltartari** [comment]
I can still get it working by setting`setopt promptsubst`, so no problem at all, @mafredri 

Thanks 👍

**Comment by ltartari** [comment]
Lol, nevermind… just updated and it seems to be fixed 🎉

Thanks again! <3
